apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxylab
  namespace: proxylab
  labels:
    app: proxylab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxylab
  template:
    metadata:
      labels:
        app: proxylab
    spec:
      volumes:
      - name: proxylab-tls
        secret:
          secretName: proxylabsecret # Edit with your Secret Name
      containers:
      - name: proxylab
        image: proxylab.azurecr.io/proxylab:latest
        ports:
        - containerPort: 8080 # Edit with your HTTP port
        - containerPort: 8443 # Edit with your HTTPS port
        volumeMounts: # 
        - name: proxylab-tls
          mountPath: /mnt/tls
          readOnly: true
        env:
        - name: HTTPPORT
          value: "8080" # Edit with your HTTP port
        - name: HTTPSPORT
          value: "8443" # Edit with your HTTPS port
        - name: USER
          value: "username_here" # Edit with your username
        - name: PASSWORD
          value: "password_here" # Edit with your password
        - name: USE_K8S_SECRET
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: proxylab
  namespace: proxylab
spec:
  selector:
    app: proxylab
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080 # Edit with your HTTP port - from ContainerPort in Deployment
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8443 # Edit with your HTTPS port - from ContainerPort in Deployment